"""Configuration constants for the prototype face engine."""

from __future__ import annotations

from pathlib import Path


DEFAULT_CAMERA_INDEX = 0
DEFAULT_CAPTURE_WIDTH = 640
DEFAULT_CAPTURE_HEIGHT = 480
DEFAULT_CAMERA_STABILIZATION_SECONDS = 1.5
MAX_CAMERA_STABILIZATION_SECONDS = 10.0
MAX_STABILIZATION_FRAME_READS = 180
POST_STABILIZATION_CAPTURE_ATTEMPTS = 5

DEFAULT_ENROLLMENT_SAMPLE_COUNT = 5
MIN_ENROLLMENT_SAMPLE_COUNT = 3
MAX_ENROLLMENT_SAMPLE_COUNT = 10
DEFAULT_LIVE_SAMPLE_COUNT = 3
MIN_LIVE_SAMPLE_COUNT = 2
MAX_LIVE_SAMPLE_COUNT = 5
MAX_ATTEMPTS_PER_SAMPLE = 3

DEFAULT_TEMPLATE_DIRECTORY = Path(__file__).resolve().parent / "data" / "templates"
DEFAULT_MODEL_DIRECTORY = Path(__file__).resolve().parent / "data" / "models"
YUNET_MODEL_FILENAME = "face_detection_yunet_2023mar.onnx"
SFACE_MODEL_FILENAME = "face_recognition_sface_2021dec.onnx"
DEFAULT_YUNET_MODEL_PATH = DEFAULT_MODEL_DIRECTORY / YUNET_MODEL_FILENAME
DEFAULT_SFACE_MODEL_PATH = DEFAULT_MODEL_DIRECTORY / SFACE_MODEL_FILENAME

YUNET_SCORE_THRESHOLD = 0.9
YUNET_NMS_THRESHOLD = 0.3
YUNET_TOP_K = 5000
YUNET_DETECTION_VALUE_COUNT = 15

SFACE_EMBEDDING_LENGTH = 128
SFACE_ALGORITHM = "opencv-yunet-2023mar-sface-2021dec"
SFACE_SIMILARITY_METRIC = "opencv-fr-norm-l2"

# Upstream OpenCV SFace LFW reference only. It is not calibrated for this camera.
DEFAULT_SFACE_L2_DISTANCE_THRESHOLD = 1.128
MAX_SFACE_L2_DISTANCE = 2.0
