"""Configuration constants for the prototype face engine."""

from __future__ import annotations

from pathlib import Path


DEFAULT_CAMERA_INDEX = 0
DEFAULT_CAPTURE_WIDTH = 640
DEFAULT_CAPTURE_HEIGHT = 480
DEFAULT_CAMERA_STABILIZATION_SECONDS = 1.5
MAX_CAMERA_STABILIZATION_SECONDS = 10.0
MAX_STABILIZATION_FRAME_READS = 180
POST_STABILIZATION_CAPTURE_ATTEMPTS = 5

DEFAULT_ENROLLMENT_SAMPLE_COUNT = 5
MIN_ENROLLMENT_SAMPLE_COUNT = 3
MAX_ENROLLMENT_SAMPLE_COUNT = 10
DEFAULT_LIVE_SAMPLE_COUNT = 3
MIN_LIVE_SAMPLE_COUNT = 2
MAX_LIVE_SAMPLE_COUNT = 5
MAX_ATTEMPTS_PER_SAMPLE = 3

FACE_WIDTH = 96
FACE_HEIGHT = 96
LBP_GRID_ROWS = 8
LBP_GRID_COLUMNS = 8
LBP_BIN_COUNT = 59
REPRESENTATION_LENGTH = LBP_GRID_ROWS * LBP_GRID_COLUMNS * LBP_BIN_COUNT
REPRESENTATION_ALGORITHM = "spatial-uniform-lbp-square-v2"

# Prototype value only. Calibrate this on captures from the deployed Pi camera.
DEFAULT_MATCH_DISTANCE_THRESHOLD = 0.35

HAAR_SCALE_FACTOR = 1.1
HAAR_MIN_NEIGHBORS = 5
HAAR_MIN_FACE_SIZE = 80
# Use an inscribed central square to avoid background and geometric stretching.
FACE_SQUARE_CROP_SCALE = 0.90

DEFAULT_TEMPLATE_DIRECTORY = Path(__file__).resolve().parent / "data" / "templates"
